version: '3.3'
services:
  django_app:
    build:
      context: ./comments
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./comments/db.sqlite3:/app/db.sqlite3
