# Generated by Django 4.2.4 on 2023-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('home_page', models.URLField(blank=True, verbose_name='Home page')),
                ('text', models.TextField(max_length=300, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Comments',
                'ordering': ['-user_name', '-email', '-created_at'],
            },
        ),
    ]
