# Generated by Django 4.2.4 on 2023-08-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentform',
            options={'ordering': ['-user_name', '-email', '-created_at'], 'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='commentform',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.commentform'),
        ),
    ]
