# Generated by Django 4.2.4 on 2023-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_commentform_options_commentform_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentform',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='commentform',
            name='parent_comments',
            field=models.ManyToManyField(blank=True, related_name='replies', to='main.commentform'),
        ),
    ]
