# Generated by Django 4.2.4 on 2023-08-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_commentform_parent_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentform',
            old_name='parent_comments',
            new_name='parent_comment',
        ),
    ]
