# Generated by Django 4.2.4 on 2023-08-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_commentform_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
