# Generated by Django 4.2.4 on 2023-08-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_commentform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentform',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='user_name',
            field=models.CharField(max_length=256, verbose_name='User name'),
        ),
    ]
