# Generated by Django 4.2.4 on 2023-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_commentform_file_alter_commentform_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentform',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image')], default='other', max_length=10),
        ),
    ]
