# Generated by Django 4.2.4 on 2023-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_commentform_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentform',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text')], default='other', max_length=10),
        ),
    ]
